export const Products = [
  {
    id: '1',
    name: 'Bolacha Trakinas',
    description: 'Whisky Americano JACK DANIELs Garrafa 750 ML',
    image_url: '../assets/jack-daniels.png',
    price: 3.09,
  },
  {
    id: '2',
    name: 'Corote',
    description: 'Whisky Americano JACK DANIELs Garrafa 750 ML',
    image_url: '../assets/jack-daniels.png',
    price: 3.89,
  },
  {
    id: '3',
    name: 'Macarrão Espaguete',
    description: 'Whisky Americano JACK DANIELs Garrafa 750 ML',
    image_url: '../assets/jack-daniels.png',
    price: 3.39,
  },
  {
    id: '4',
    name: 'Bacon',
    description: 'Whisky Americano JACK DANIELs Garrafa 750 ML',
    image_url: '../assets/jack-daniels.png',
    price: 5.59,
  },
  {
    id: '5',
    name: "Jack Daniel's",
    description: 'Whisky Americano JACK DANIELs Garrafa 750 ML',
    image_url: '../assets/jack-daniels.png',
    price: 95.99,
  },
  {
    id: '6',
    name: 'Red Bull',
    description: 'Whisky Americano JACK DANIELs Garrafa 750 ML',
    image_url: '../assets/jack-daniels.png',
    price: 7.99,
  },
  {
    id: '7',
    name: 'Chocolate',
    description: 'Whisky Americano JACK DANIELs Garrafa 750 ML',
    image_url: '../assets/jack-daniels.png',
    price: 7.99,
  },
];
